name: My first workflow

on: [push, workflow_dispatch]

jobs:
  my-prod-job:
    environment: Prod
    runs-on: ubuntu-latest

    steps:
      - name: Print secret
        run: echo ${{ secrets.MY_AWS_SECRET }}

      - name: Print app URL
        run: echo ${{ vars.APP_URL }}

  my-test-job:
    environment: Test
    runs-on: ubuntu-latest

    steps:
      - name: Print secret
        run: echo ${{ secrets.MY_AWS_SECRET }}

      - name: Print app URL
        run: echo ${{ vars.APP_URL }}
