name: My first workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  my-first-job:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
      - run: echo "This is my first jobs"

  my-second-job:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest

    steps:
      - run: echo "This is my second job"
