name: My first workflow

on:
  push:
    branches:
      - main
      - develop


jobs:
  my-prod-job:
    environment: Prod
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{github.ref_name}}
